[plugins]
cloud-buildLogic-spotless = { id = "org.incendo.cloud-build-logic.spotless", version.ref = "cloud-build-logic" }
cloud-buildLogic-rootProject-publishing = { id = "org.incendo.cloud-build-logic.publishing.root-project", version.ref = "cloud-build-logic" }
cloud-buildLogic-rootProject-spotless = { id = "org.incendo.cloud-build-logic.spotless.root-project", version.ref = "cloud-build-logic" }

[versions]
cloud-build-logic = "0.0.15"
ktlint = "1.0.1"
checkstyle = "10.12.5"

# Kotlin
kotlin = "1.9.22"
dokka = "1.9.10"
coroutines = "1.7.3"

# Cloud
cloud = "2.0.0-rc.1"

# External
immutables = "2.10.1"
javacord = "3.8.0"
jda = "4.4.1_353"
jda5 = "5.0.0-beta.24"
logback = "1.4.14"
kord = "0.13.1"
kotlinLogging = "6.0.9"
discord4j = "3.2.6"
slf4j = "2.0.12"
log4j = "2.23.1"

# Test
jupiterEngine = "5.10.2"
mockitoCore = "4.11.0"
mockitoJupiter = "4.11.0"
mockitoKotlin = "5.2.1"
truth = "1.4.1"

[libraries]
cloud-build-logic = { module = "org.incendo:cloud-build-logic", version.ref = "cloud-build-logic" }
gradleKotlinJvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
gradleDokka = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }

# Cloud
cloud-core = { group = "org.incendo", name = "cloud-core", version.ref = "cloud" }
cloud-annotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloud" }
cloud-kotlin-coroutines = { group = "org.incendo", name = "cloud-kotlin-coroutines", version.ref = "cloud" }
cloud-kotlin-coroutines-annotations = { group = "org.incendo", name = "cloud-kotlin-coroutines-annotations", version.ref = "cloud"}
cloud-kotlin-extensions = { group = "org.incendo", name = "cloud-kotlin-extensions", version.ref = "cloud" }

# External
immutables = { group = "org.immutables", name = "value", version.ref = "immutables" }
javacord = { group = "org.javacord", name = "javacord", version.ref = "javacord" }
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }
jda5 = { group = "net.dv8tion", name = "JDA", version.ref = "jda5" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
kord = { group = "dev.kord", name = "kord-core", version.ref = "kord" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlinLogging" }
discord4j = { group = "com.discord4j", name = "discord4j-core", version.ref = "discord4j" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
log4j = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }

# Kotlin
coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutinesJdk8 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-jdk8", version.ref = "coroutines" }

# Test
jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "jupiterEngine" }
jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiterEngine" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockito-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockitoJupiter" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }

[bundles]
coroutines = ["coroutinesCore", "coroutinesJdk8"]
